version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pastebin
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db

  air:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /app
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./:/app/

volumes:
  dbdata:
