basePath: /api/v1
definitions:
  entity.ForgotPasswordRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  entity.Post:
    properties:
      content:
        type: string
      title:
        type: string
    required:
    - content
    - title
    type: object
  entity.ResetPasswordRequest:
    properties:
      password:
        type: string
      passwordConfirmation:
        type: string
    required:
    - password
    - passwordConfirmation
    type: object
  entity.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
  entity.SigninRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  entity.SigninResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  entity.SignupResponse:
    properties:
      acessToken:
        type: string
    type: object
  entity.User:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/forgot-password:
    post:
      consumes:
      - application/json
      description: Submit a request to reset the user's password by providing their
        email address.
      parameters:
      - description: User's email
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email sent successfully
          schema:
            $ref: '#/definitions/entity.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entity.Response'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/entity.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Response'
      summary: Submit a request to reset the user's password
      tags:
      - Auth
  /auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Refresh the user's access token by providing a valid refresh token.
      parameters:
      - description: refresh token
        in: header
        name: refresh
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Refreshed successfully
          schema:
            $ref: '#/definitions/entity.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entity.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Response'
      summary: Refresh the user's access token
      tags:
      - Auth
  /auth/reset-password/{resetToken}:
    put:
      consumes:
      - application/json
      description: Reset the user's password by providing a valid reset token and
        the new password.
      parameters:
      - description: User's email
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Password updated successfully
          schema:
            $ref: '#/definitions/entity.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entity.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.Response'
      summary: Reset the user's password using a reset token
      tags:
      - Auth
  /auth/signin:
    post:
      consumes:
      - application/json
      description: authenticates a user
      parameters:
      - description: User
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.SigninRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.SigninResponse'
      summary: Authenticate user
      tags:
      - Auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: User
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.SignupResponse'
      summary: Create account
      tags:
      - Auth
  /post/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a post belonging to the logged-in user on the platform
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Post deleted successfully
          schema:
            $ref: '#/definitions/entity.Response'
      security:
      - BearerAuth: []
      summary: Delete a post by ID
      tags:
      - Post
  /post/all:
    get:
      consumes:
      - application/json
      description: Get all posts of the logged-in user on the platform
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Response'
            type: array
      security:
      - BearerAuth: []
      summary: Get all posts of the logged-in user
      tags:
      - Post
  /post/create:
    post:
      consumes:
      - application/json
      description: create a post on the platform
      parameters:
      - description: Post
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/entity.Post'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Response'
      summary: Create a post
      tags:
      - Post
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
